using System;
using System.Collections.Generic;
using System.Text;

namespace Digitale_Geraeteliste.Core.Model
{
    public class LendItem
    {
        public int Id { get; set; } // PK
        public DateTime LendDate { get; set; }
        public DateTime ExpectedReturnDate { get; set; }
        public DateTime? ActualReturnDate { get; set; }
        public Employee BorrowedBy { get; set; } = null!;
        public int BorrowedById { get; set; } // FK
        public Item Item { get; set; } = null!;
        public int ItemId { get; set; } // FK
        public Employee LendBy { get; set; } = null!;
        public int LendById { get; set; } // FK
        public bool IsActive { get; set; } = true;
        public bool IsOverdue => IsOverdueAt(DateTime.Now.Date);
        public string AffiliatedContractNumber { get; set; } = string.Empty;

        public LendItem(DateTime lendDate, DateTime expectedReturnDate, Employee borrowedBy, Item item, Employee lendBy, string affiliatedContractNumber)
        {
            Id = 0; // Id is set to 0 because it will be generated by the database when the item is added to the database
            LendDate = lendDate;
            ExpectedReturnDate = expectedReturnDate;
            BorrowedBy = borrowedBy;
            Item = item;
            LendBy = lendBy;
            AffiliatedContractNumber = affiliatedContractNumber;
        }
        public LendItem(DateTime lendDate, DateTime expectedReturnDate, Employee borrowedBy, Item item, Employee lendBy, string affiliatedContractNumber, DateTime? actualReturnDate)
        {
            Id = 0; // Id is set to 0 because it will be generated by the database when the item is added to the database
            LendDate = lendDate;
            ExpectedReturnDate = expectedReturnDate;
            BorrowedBy = borrowedBy;
            Item = item;                                                // Constructor for Import of old data from CSV file
            LendBy = lendBy;
            AffiliatedContractNumber = affiliatedContractNumber;
            ActualReturnDate = actualReturnDate;
        }

        private LendItem() { }

        public void LendItemToEmployee(Employee employee, DateTime lendDate, Item item, Employee lendBy, string affiliatedContractNumber, int id)
        {
            BorrowedBy = employee;
            LendDate = lendDate;
            ExpectedReturnDate = LendDate.AddDays(Item.StandardLendDuration);
            Id = id;
            Item = item;
            LendBy = lendBy;
            AffiliatedContractNumber = affiliatedContractNumber;
        }

        public void LendItemToEmployee(Employee employee, DateTime lendDate, Item item, Employee lendBy, string affiliatedContractNumber, int id, int duration)
        {
            BorrowedBy = employee;
            LendDate = lendDate;
            ExpectedReturnDate = LendDate.AddDays(duration);
            Id = id;
            Item = item;
            LendBy = lendBy;
            AffiliatedContractNumber = affiliatedContractNumber;
        }
        public bool IsOverdueAt(DateTime dayToCheck) => ActualReturnDate == null && dayToCheck > ExpectedReturnDate; // unit testable method to check if the item is overdue at a specific date

        public void ReturnItem(DateTime returnDate)
        {
            ActualReturnDate = returnDate;
            IsActive = false;
        }
    }
}
